# Version of config file
version: 1.2.0

# Server's listening port (default: 7054)
port: 7054

# Enables debug logging (default: false)
debug: false

# TLS section for the server's listening port
tls:
  # Enable TLS (default: false)
  enabled: true

# CA section
ca:
  # Name of this CA
  name: Org1CA

# Registry section
registry:
  # Contains identity information which is used when LDAP is disabled
  identities:
     - name: admin
       pass: adminpw
       #-for-kizilay
       type: client
       affiliation: ""
       attrs:
          hf.Registrar.Roles: "*"
          hf.Registrar.DelegateRoles: "*"
          hf.Revoker: true
          hf.IntermediateCA: true
          hf.GenCRL: true
          hf.Registrar.Attributes: "*"
          hf.AffiliationMgr: true

# Signing section
signing:
    default:
      usage:
        - digital signature
      expiry: 8760h

# Certificate Signing Request (CSR) section
csr:
   cn: ca.org1.example.com
   hosts:
     - localhost
     - org1.example.com
   ca:
      expiry: 131400h

# BCCSP (BlockChain Crypto Service Provider) section
bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            # The directory used for the software file-based keystore
            keystore: msp/keystore
